const Discord = require('discord.js'); // Loading up Discord API
const musicLib = require('./musicCommands');
const botCommands = require('./botCommands'); // Loading up bot functions


/* New calls a constructor defining the bot client according to the loaded 
 Discord API */

//var token = 'MTY4MjAxOTA0MDQyNjcyMTI4.C2NCDw.vE2-dyHLXBZaUkyGe-gidJu5P8w' //Bot's unique identifier as generated by Discord. Yeah take the token see if I care
var token = 'MTY4MjAxOTA0MDQyNjcyMTI4.C2ed6A.cbHUHqlbi9OfM991XpOBcD0PCZ0'
const bot = new Discord.Client(); 
const command = new botCommands();
const music = new musicLib();

setInterval(save => {command.salvarMick(bot)},5000); 
command.rise(bot,token);
command.vigilance(bot);
command.replies(bot);
music.radio(bot);
