const Discord = require('discord.js'); // Loading up Discord API
const musicLib = require('./musicCommands');
const botCommands = require('./botCommands'); // Loading up bot functions


/* New calls a constructor defining the bot client according to the loaded 
 Discord API */

var token = 'MTY4MjAxOTA0MDQyNjcyMTI4.C1TlOg.eVtHz4c4_58RYEtQCIoj7zjLm2Q' //Bot's unique identifier as generated by Discord.
const bot = new Discord.Client(); 
const command = new botCommands();
const music = new musicLib();

command.rise(bot,token);
command.vigilance(bot);
command.replies(bot);
music.radio(bot);